#### 2 | Even Fibonacci numbers
"
https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the 
previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do 
not exceed four million, find the sum of the even-valued terms.
"

get_fib_seq <- function(n, golden_ratio) {
  "
  Computes Fibonacci Sequence in Closed Form.
  http://en.wikipedia.org/wiki/Fibonacci_number#Closed-form_expression
  "
  return((golden_ratio^n - (-golden_ratio)^-n) / sqrt(5)) # Binet's formula
}

upper_bound <- 4e6
golden_ratio = (1 + sqrt(5)) / 2

# How many nrs are in the fib sequence up to upper_bound? From Binet's formula 
len_fib_seq <- floor((log(upper_bound) + log(5) / 2) / log(golden_ratio))

# Computes Fibonacci's sequence
fib_seq <- sapply(2:len_fib_seq, get_fib_seq, golden_ratio = golden_ratio)
nr_idxs <- which(fib_seq <= upper_bound & round(fib_seq %% 2L) == 1)
sum(fib_seq[nr_idxs])