# 12 | Highly divisible triangular number
# https://projecteuler.net/problem=12
# 
# The sequence of triangle numbers is generated by adding the natural numbers. 
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
# The first ten terms would be:
#   
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# 
# Let us list the factors of the first seven triangle numbers:
#   
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
# 
# What is the value of the first triangle number to have over five 
# hundred divisors?

ct <- 2L
stop_here <- F # stop criteria

while (!stop_here) {
 
  tri_nr <- sum(1:ct) # computes triangular nr

 cap <- floor(sqrt(tri_nr)) # just checks for these cases
 nrs <- 1:cap
 
 idxs <- which(tri_nr %% nrs == 0L)
 factors <- c(nrs[idxs], tri_nr / nrs[idxs]) # computes factors of tri_nr
 
 ct <- ct + 1L
 stop_here <- length(factors) > 500L # updates stop criteria
}
print(tri_nr)
