# 2 | Even Fibonacci numbers
# https://projecteuler.net/problem=2
# 
# Each new term in the Fibonacci sequence is generated by adding the 
# previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do 
# not exceed four million, find the sum of the even-valued terms.

# To solve this problem my favorite solutions are:
# - using Binet's formula that gives a closed form solution
# - using the fact that the even values repeat every 3rd number

#### Closed form ####

upper_bound <- 4e6-1
golden_ratio <- (1 + sqrt(5)) / 2

get_fib_seq <- function(n, golden_ratio) {
  "
  Computes Fibonacci Sequence in Closed Form.
  http://en.wikipedia.org/wiki/Fibonacci_number#Closed-form_expression
  "
  return((golden_ratio^n - (-golden_ratio)^-n) / sqrt(5)) # Binet's formula
}

# How many nrs are in the fib sequence up to upper_bound? From Binet's formula: 
len_fib_seq <- floor((log(upper_bound) + log(5) / 2) / log(golden_ratio))

# Compute Fibonacci's sequence
fib_seq <- get_fib_seq(1:len_fib_seq, golden_ratio)
idxs <- which(fib_seq <= upper_bound & round(fib_seq %% 2L) == 1L)

print(sum(fib_seq[idxs]))

#### Another solution ####

get_fib_seq(1:15, golden_ratio)
# Seems that every 3rd number is even, let's prove it

# E(n) = E(n-1) + E(n-2), for n > 2
# E(n) = E(n-1) + E(n-2) =
# = 2 * E(n-2) + E(n-3) =
# = 2 * (E(n-3) + E(n-4)) + E(n-3) = 
# = 3 * E(n-3) + 2 * E(n-4)
# = 3 * E(n-3) + E(n-4) + E(n-5) + E(n-6) =
# = 4 * E(n-3) + E(n-6)

# thus we can loop till upper_bound and sum all 3rd numbers.

# There is also an interesting result at
# http://www.mathblog.dk/project-euler-25-fibonacci-sequence-1000-digits/
# it allows us to know what is the first fib number with a certain nr of digits
