# 45 | Triangular, pentagonal, and hexagonal
# https://projecteuler.net/problem=45
# 
# Triangle, pentagonal, and hexagonal numbers are
# generated by the following formulae:
#   
# Triangle   	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# 
# It can be verified that T285 = P165 = H143 = 40755.
# 
# Find the next triangle number that is also pentagonal and hexagonal.

get_tri_nr <- function(nr) {
  return(nr * (nr + 1) / 2)
}

get_pent_nr <- function(nr) {
  return(nr * (3 * nr - 1) / 2)
}

get_hex_nr <- function(nr) {
  return(nr * (2 * nr - 1))
}

nr <- 286
while (nr > 0) {
    if (get_tri_nr(nr) %in% get_pent_nr(2:nr) & get_tri_nr(
      nr) %in% get_hex_nr(2:nr)) {
      break
    }
    nr <- nr + 1
}

print(get_tri_nr(nr))
